### PR TITLE
Support new Ruby versions and remove old ones

### PR DESCRIPTION
**Pull request by javierjulio**
This is a general update to the Travis config to make sure that it uses:

* the latest rubygems and bundler
* newer versions of Ruby and JRuby
* drops support for Ruby 2.2 and below
* drops support for ActiveSupport 3
* adds ActiveSupport 5 build series
* remove empty build `- # rbx` line which caused another set of 1.9.3 tests to run!
* uses 4.2.x series for any ActiveSupport 4 related builds

### CODE REVIEW

**Comment by javierjulio** [comment]
The failures for Ruby 2.1 are just because of one failing test that has been occurring in older clockwork builds too but since its not a consistent failure I wonder if there is some random aspect to the test case that causes the failure:

```
  1) Failure:
Clockwork#test_0005_should pass all arguments to every [/home/travis/build/Rykian/clockwork/test/clockwork_test.rb:72]:
Failed assertion, no message given.
```

Since this update includes Ruby 2.4 whereas it wasn't before, its failing but only for ActiveSupport 3 and 4 versions. The version 5 build is passing. I'm not sure if the preference is to only rely on current ActiveSupport versions for current Ruby versions or to resolve the issue?

**Comment by javierjulio** [comment]
@Rykian the failures for Ruby 2.1 and JRuby are just because of one failing test that has been occurring in older clockwork builds too but since its an intermittent failure I wonder if there is some unexpected state to the test case that causes the failure:

```
  1) Failure:
Clockwork#test_0005_should pass all arguments to every [/home/travis/build/Rykian/clockwork/test/clockwork_test.rb:72]:
Failed assertion, no message given.
```

Note after doing some force pushes here, the latest one doesn't have this failure now!

Since this update includes Ruby 2.4 whereas it wasn't before, its failing but only for ActiveSupport 3 and 4 versions. The version 5 build is passing. I'm not sure if the preference is to only rely on say ActiveSupport 5 for current Ruby 2.4+?

**Comment by Rykian** [comment]
Sorry for the very very (very) late response, but maybe it's time to bump to a 3.0 and drop non-supported ruby versions?

**Comment by javierjulio** [comment]
No problem at all. Sure, I can update it. What is the lowest you’d want for Ruby and ActiveSupport version?

**Comment by javierjulio** [comment]
@Rykian I updated the config to only use Ruby 2.3+ and ActiveSupport 4+ versions. Is that ok? Let me know if you prefer something else. I went with that as Ruby 2.2 is EOL but 2.3 is still in security maintenance.

**Comment by javierjulio** [comment]
@Rykian the build is now green! 💪🏻 This is ready for you.

The issue with the Ruby2.4/ActiveSupport4 failing build was that activesupport 4.0.x series was being installed rather than 4.2.x. The issue was the mintiest dependency version as 5.x.x is required for activesupport 4.2.x to install.

Details for that change and all the others are in the commit messages. Let me know if there is anything else. Perhaps we want to add a `required_ruby_version = '>= 2.3'` to the gemspec file too?

**Comment by Rykian** [comment]
Nice work, thank you!

> Details for that change and all the others are in the commit messages. Let me know if there is anything else. Perhaps we want to add a `required_ruby_version = '>= 2.3'` to the gemspec file too?

activesupport 4.2 still support old ruby versions (1.9), so I don't know. I don't want to handle problems with old libs but I don't want to lock users more than we need. It will be at their own risks :)

I will squash/merge this tomorrow.

**Comment by javierjulio** [comment]
No problem! Yes I realize now when I made that change I was thinking of Ruby standalone from what versions of ActiveSupport is supported. Sorry about that. Let me know what you think is best and I can make any other changes. Thanks! ❤️

**Comment by Rykian** [comment]
That's fine for me :) Thanks ;)

**Pull request merged**
